spring:
  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.example.mybatisstarter.model
  configuration:
    map-underscore-to-camel-case: true

