spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.example.mybatisstarter.model
  configuration:
    map-underscore-to-camel-case: true

